#!/bin/sh

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA

ID=$1
FN=""
MAIL_DIR=~/mail/
MAIL_BOX=("mb1" "mb2")

function do_grep()
{
	local DIR=$1
	FN=`egrep -R --files-with-matches -e "Message-[IiDd]{2}: <${ID}>" ${DIR}`
}

function main()
{
	if [ "z${ID}" == "z" ]; then
		echo "No Message-ID was provided"
		exit 1
	fi

	for _mb in "${MAIL_BOX[@]}"; do
		mb="${MAIL_DIR}/${_mb}/new"

		do_grep ${mb}
		if [ "z$FN" != "z" ]; then
			break
		fi

		mb="${MAIL_DIR}/${_mb}/cur"
		do_grep ${mb}
		if [ "z$FN" != "z" ]; then
			break
		fi
	done

	if [ "z$FN" == "z" ]; then
		echo "Can't find ${ID}"
		exit 1
	fi

	if [ -f ~/_linux/scripts/checkpatch.pl ]; then
		~/_linux/scripts/checkpatch.pl ${FN}
	fi

	git am ${FN}
	echo

	exit 0
}

main
